title: Chaffee's Homepage
description: Welcome to my homepage
show_downloads: false
google_analytics: 6410311703
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
